title: Anders Risager Kristensen
description: Portfolio
url: "https://USERNAME.github.io"
baseurl: "/portfolio"

collections:
  projects:
    output: true
    permalink: /projects/:name/

markdown: kramdown